Fix/blake2b signiture
Topl/BramblPy pull request #105
Opened 2021-07-10 13:12 UTC by rromic

Changed hash algorithm to use `blake2b` instead of `keccak256` for extracting mac value.
Changed proposition and signature format to correct one.
Changed keys from JSON response body to extract `rawTx` values.
Updated Unit test getMAC.

2021-07-12 15:22 UTC, sterlingwellscaffeine requested changes
@rromic Would you be able to add unit testing around the addSigToTx method in addition to the unit test for the getMac method? 

I have left some other feedback to make sure that this PR adheres to our cryptography spec as well as to clarify some decisions that were made here.

Thanks in advance,

Sterling

2021-07-12 15:22 UTC, sterlingwellscaffeine commented on brambl/Brambl.py
> +        for key in prototypeTxDic['result']['txId']:
Could you explain your reasoning behind changing the format of the input json (prototypeTx) to this function?

2021-07-12 15:22 UTC, sterlingwellscaffeine commented on brambl/modules/KeyManager.py
> +    :type derivedKey: bytes string
if the derivedKey is bytes, could you delete the string part of this documentation? If not, could you revert this change?

2021-07-12 15:22 UTC, sterlingwellscaffeine commented on brambl/modules/KeyManager.py
> +    blake = BLAKE2b.new(digest_bits=256)
In BramblJS, the digestLength is 32 while here the digest_bits are 256. Could you explain the discrepancy here? Has there been thorough testing to make sure that this does not make a difference?

2021-07-12 15:22 UTC, sterlingwellscaffeine commented on tests/testScripts/unitTest.py
> +        self.assertEqual(KeyManager.getMAC(b'\xcc\xe43\xb6\xe3Q\x07\xf5\xbb\xf3\x0e1k\x01\xf5"\x11IO2iX4\xda:\xf3!\x1e0\xd3-\r',
Did you use your getMac function to generate the output value? In that case, the test would be circular. If you calculated the mac value by hand, then this is ok.

2021-07-12 16:47 UTC, rromic commented on brambl/Brambl.py
> +        for key in prototypeTxDic['result']['txId']:
Basically createRawTransfer doesn't have anymore key `formattedTx` in JSON response body, instead it returns key:
```
result: 
         rawTx:

```
exp. 
`{'jsonrpc': '2.0', 'id': 'e7789f19-c540-4f04-b9ba-5e424d7172f6', 'result': {'rawTx': {'txType': 'AssetTransfer', 'timestamp': 1626104397373, 'signatures': {}, 'newBoxes': [{'nonce': '2149736382704735321', 'id': 'EgyDSm5Yz8GfkvvPnaJfXnDvBiTK4nSmzFANq4STWt8H', 'evidence': 'YYTe1t1hHa429em6yDzCFsRakUJjhSynFPpKjFJ2uQMu', 'type': 'PolyBox', 'value': {'type': 'Simple', 'quantity': '4800'}}, {'nonce': '1312804140406069949', 'id': 'AzDS9YnqiWYDMhbpDjGPA6ZHi3uibotrYPxW9k1ELiHL', 'evidence': 'YYTe1t1hHa429em6yDzCFsRakUJjhSynFPpKjFJ2uQMu', 'type': 'AssetBox', 'value': {'quantity': '1', 'assetCode': '5YJR24BDmDJuZPeDRCn7TPy96qtxDUDLHs22RVWUXDm2jcAJGzK9DysDM1', 'metadata': 'cocoa transaction e7789f19-c540-4f04-b9ba-5e424d7172f6', 'type': 'Asset', 'securityRoot': '7dqWYvKyH5MKJDSvVDDTB5L5Vv2LQyzVfHS98GSjvdck'}}], 'data': '{"quantity": "10", "price": "100.01", "currency": "GHC", "payee_id": "momo response", "date": "07/12/2021"}', 'to': [['3NLeYvHanEmMZLW7bvBsKAV5bvZaGqmiS4gz9FPitEMTdvF51dod', {'type': 'Simple', 'quantity': '4800'}], ['3NLeYvHanEmMZLW7bvBsKAV5bvZaGqmiS4gz9FPitEMTdvF51dod', {'quantity': '1', 'assetCode': '5YJR24BDmDJuZPeDRCn7TPy96qtxDUDLHs22RVWUXDm2jcAJGzK9DysDM1', 'metadata': 'cocoa transaction e7789f19-c540-4f04-b9ba-5e424d7172f6', 'type': 'Asset', 'securityRoot': '7dqWYvKyH5MKJDSvVDDTB5L5Vv2LQyzVfHS98GSjvdck'}]], 'propositionType': 'PublicKeyCurve25519', 'from': [['3NLeYvHanEmMZLW7bvBsKAV5bvZaGqmiS4gz9FPitEMTdvF51dod', '-3694647291444886373']], 'minting': True, 'txId': 'pcrvnEse27woodXV7FZ83qm9o1mgN6EtVdXAVrAKnyjs', 'boxesToRemove': ['AbmpiZnGmtWb6KyFNhAqMNf4TAtdo98AMbhARems7zSV'], 'fee': '100'}, 'messageToSign': '4DoyoG2rAaqjk3z8PLwKm7vJmNkyWGhB3GW3dybUV8QhAhSeXqM9fXFcGBfP3nvE3BZsSb2FVFJ8PuGWQXaQJ8K99t6ZfKKe6Wd9Ux4LzhgxXF7GRUHPz6qkUURxRR4dudUniixmVSApRv66pynV4rmVCyNRqnbyZ86VHnZCoFuxsMavHf2qicvh85hRkazcPcpvjswVXkfuVfACbNGPvcMRCAcF8TirFkSFTdBfCCwMrgZQcjpQE8EHvfS7y6KofGSwsZzemiRHeY8aKr9t8bjZTWWcH6Vy5oPRENeu1hQ8KbxKHPyW48oHhAHWRzbjVLSneFi4x82ZBisDNzE6K8Dj5v2CPJrZ639nic45rNYxfqBEe9RBfda9TBLE8JZwRxSijnR5esrAdEjcWTzNN2Dq9oePLTijhHoEFcnnesRirW9pdpUiM7yx3hvBiEbXxe8Q9u44grekiBXZBRPAv9Vqq3DF3aG4wb81eCsvZ6cnjpYQBBZBwbC8FsfZUySvrAMGdmsYp1FE5ovVZQhWkTeAeQ56UhtRgsfLBo5oHPuNZtbs3EmQt'}}`

Here is my tip feller :D it should be rawTx instead of txId, gonna fix this.

2021-07-12 16:47 UTC, rromic commented on brambl/modules/KeyManager.py
> +    :type derivedKey: bytes string
it shoud be only bytes, gonna fix it

2021-07-12 16:49 UTC, rromic commented on tests/testScripts/unitTest.py
> +        self.assertEqual(KeyManager.getMAC(b'\xcc\xe43\xb6\xe3Q\x07\xf5\xbb\xf3\x0e1k\x01\xf5"\x11IO2iX4\xda:\xf3!\x1e0\xd3-\r',
the output value I got calculated from BramlJS :)

2021-07-12 16:52 UTC, rromic commented on brambl/modules/KeyManager.py
> +    blake = BLAKE2b.new(digest_bits=256)
in BramlJS digestLength is represent in bytes and here it's represented in bits, so basically it's the same thing :) 
256 bits are equal to 256/8 - 32 bytes

2021-07-12 16:54 UTC, rromic reviewed
I'll also add unit test for addSigToTx method for sure. Thanks for suggestions and comments!

2021-08-10 08:20 UTC, rromic commented on brambl/Brambl.py
> +        for key in prototypeTxDic['result']['txId']:
fixed, now it getting value from dictionary for a key rawTx

2021-08-10 08:21 UTC, rromic commented on brambl/modules/KeyManager.py
> +    :type derivedKey: bytes string
fixed

2021-08-10 08:23 UTC, rromic commented
unit test for addSigToTx is now done, I've used mock lib to mock method urandom (from os package) so we can have fixed value and verify results.

2021-08-11 15:52 UTC, merged