Added JSON-RPC method class and definitions
Topl/BramblPy pull request #117
Opened 2021-11-05 14:46 UTC by sterlingwellscaffeine

## Purpose

1.) Added generic method class and defined all JSON-RPC routes

## Approach

1.) A generic module (in this case the requests module) will handle the calls done by the method class. 
I want to expand this class with formatters and validators but will do that at a later point, for now it is very minimal. 

## Testing

Unit testing of the method class. 

## Tickets

2021-11-18 20:39 UTC, scasplte2 requested changes
overall nicely done, I like the structure of the RPC. If you can address my two comments we can merge

2021-11-18 20:39 UTC, scasplte2 commented on brambl/Brambl.py
>  validTxMethods = ['createAssetsPrototype', 'transferAssetsPrototype', 'transferTargetAssetsPrototype']
do you use this anywhere? the targetAsset thing is deprecated so I'm pretty sure this line can be removed

2021-11-18 20:39 UTC, scasplte2 commented on brambl/Brambl.py
>  class Brambl:
perhaps I don't read python well but it seems like this is a very different scheme for Brambl organization from at least JS. In that one the Brambl instance is the key object that everything flows through. Is that still the case here?

2021-11-18 20:40 UTC, sterlingwellscaffeine commented on brambl/Brambl.py
>  validTxMethods = ['createAssetsPrototype', 'transferAssetsPrototype', 'transferTargetAssetsPrototype']
No, that is a hold over from the code that was previously there. Good catch that will be fixed.

2021-11-18 20:47 UTC, sterlingwellscaffeine commented on brambl/Brambl.py
>  class Brambl:
It is more similar to the "Requests" class in JS. Potentially I should add the CredentialManager to the Brambl instance as well?

2021-11-18 20:49 UTC, sterlingwellscaffeine commented on brambl/Brambl.py
>  validTxMethods = ['createAssetsPrototype', 'transferAssetsPrototype', 'transferTargetAssetsPrototype']
Fixed in most recent commit.

2021-11-30 14:40 UTC, scasplte2 commented on brambl/Brambl.py
>  class Brambl:
maybe we can just talk about it today but I'd like to discuss the entire structure so it is clear in my head

2021-11-30 14:40 UTC, merged

2021-11-30 14:42 UTC, sterlingwellscaffeine commented on brambl/Brambl.py
>  class Brambl:
Yes, we should definitely do some knowledge transfer as well when we get an opportunity.